<script setup lang="ts">
import { onShow } from '@dcloudio/uni-app'
import dayjs from 'dayjs'
import { computed, shallowRef } from 'vue'
import type { components } from '@/api/types/generated'
import { createExposureBid, getCurrentExposure, getExposureBid, getExposureBidByIdempotencyKey, getExposureCarousel, getExposureRules, listExposureBids } from '@/api/exposure'
import { getMyTag, getPublicTag } from '@/api/social'
import AppHeader from '@/components/business/AppHeader.vue'
import AsyncState from '@/components/ui/AsyncState.vue'
import { goBack } from '@/utils/navigation'

type Current=components['schemas']['ExposureCurrent']; type Rules=components['schemas']['ExposureRules']; type Bid=components['schemas']['ExposureBid']; type Carousel=components['schemas']['ExposureCarouselItem']
const current=shallowRef<Current|null>(null), rules=shallowRef<Rules|null>(null), bids=shallowRef<Bid[]>([]), carousel=shallowRef<Carousel[]>([])
const carouselTitles=shallowRef<Record<string,string>>({})
const tagId=shallowRef(''), tagVersion=shallowRef(0), amount=shallowRef(''), loading=shallowRef(false), submitting=shallowRef(false), error=shallowRef('')
const lookupKey=shallowRef(''),lookupResult=shallowRef<Bid|null>(null)
const minimum= computed(()=> current.value?.minimumBid || rules.value?.openingBid || '0')
function formatTime(value?:string|null){if(!value)return'—';const time=dayjs(value);return time.isValid()?time.format('MM-DD HH:mm'):value}
function carouselLabel(item:Carousel){const id=item.tagId||'';return carouselTitles.value[id]||(id?`Tag ${id.slice(0,8)}`:'—')}
async function load(){loading.value=true;error.value='';try{const [c,r,b,ca,m]=await Promise.all([getCurrentExposure(),getExposureRules(),listExposureBids({limit:30}),getExposureCarousel({limit:20}),getMyTag()]);current.value=c;rules.value=r;bids.value=b.items;carousel.value=ca.items||[];const own=m.active||m.draft;tagId.value=own?.id||'';tagVersion.value=own?.version||0;if(!amount.value)amount.value=minimum.value
  const ids=(ca.items||[]).map(item=>item.tagId).filter((id):id is string=>Boolean(id))
  if(ids.length){const titles:Record<string,string>={};await Promise.all(ids.map(async id=>{try{const tag=await getPublicTag(id);titles[id]=tag.body.startsWith('#')?tag.body:`# ${tag.body}`}catch{titles[id]=`Tag ${id.slice(0,8)}`}}));carouselTitles.value=titles}
}catch(cause){error.value=cause instanceof Error?cause.message:'曝光信息加载失败'}finally{loading.value=false}}
async function submit(){if(!tagId.value)return uni.showToast({title:'请先发布一个 Tag',icon:'none'});submitting.value=true;try{lookupKey.value=`exposure-${Date.now()}-${Math.random().toString(16).slice(2)}`;const result=await createExposureBid({tagId:tagId.value,tagVersion:tagVersion.value,offeredCoin:amount.value},lookupKey.value);await getExposureBid(result.bidId);lookupResult.value=await getExposureBidByIdempotencyKey(lookupKey.value);await load();uni.showToast({title:result.status==='ACCEPTED'?'竞价成功':'竞价未通过',icon:'none'})}finally{submitting.value=false}}
async function lookupBid(){if(!lookupKey.value.trim())return;submitting.value=true;try{lookupResult.value=await getExposureBidByIdempotencyKey(lookupKey.value.trim())}finally{submitting.value=false}}
function openWallet(){uni.navigateTo({url:'/pages/gift/timeline'})} onShow(load)
</script>
<template><view class="tago-page tago-page--detail exposure-page"><AppHeader back title="竞拍规则" subtitle="让认真表达被更多人看见" @back="goBack"/><AsyncState :loading="loading" :error="error" @retry="load"><view class="exposure-content"><section class="top-note"><text>当前 TOP</text><b>{{ current?.paidCoin || '—' }} T币</b><small>{{ current?.expiresAt ? `持续至 ${formatTime(current.expiresAt)}` : '暂时没有置顶 Tag' }}</small></section><section class="paper bid-box"><text class="title">为我的 Tag 竞价</text><text class="hint">最低 {{ minimum }} T币 · 每次至少加 {{ rules?.minimumIncrement || '—' }} · 权益 {{ rules ? Math.round(rules.entitlementSeconds / 60) : '—' }} 分钟</text><input v-model="amount" type="digit" placeholder="输入 T 币数量"/><button :loading="submitting" @click="submit">提交即时竞价</button><button class="wallet-link" @click="openWallet">查看钱包与代币 →</button></section><section class="paper lookup-box"><text class="title">按幂等键找回竞价</text><text class="hint">网络中断后，也能找回同一次提交的真实结果</text><view><input v-model="lookupKey" placeholder="输入或使用最近一次提交键"/><button :loading="submitting" @click="lookupBid">查询</button></view><text v-if="lookupResult" class="lookup-result">{{ lookupResult.status }} · {{ lookupResult.offeredCoin }} T币 · {{ lookupResult.bidId }}</text></section><section class="paper"><text class="title">正在轮播</text><view v-if="carousel.length" class="rows"><view v-for="item in carousel" :key="item.entitlementId" class="row"><text>{{ carouselLabel(item) }}</text><b>{{ item.paidCoin }} T币</b></view></view><text v-else class="empty">当前没有轮播记录</text></section><section class="paper"><text class="title">我的竞价记录</text><view v-if="bids.length" class="rows"><view v-for="bid in bids" :key="bid.bidId" class="row"><view><text>{{ bid.offeredCoin }} T币</text><small>{{ formatTime(bid.createdAt) }}</small></view><b :class="`status--${bid.status.toLowerCase()}`">{{ bid.status==='ACCEPTED'?'已接受':'未通过' }}</b></view></view><text v-else class="empty">还没有提交过竞价</text></section></view></AsyncState></view></template>
<style scoped lang="scss">.exposure-content{display:flex;flex-direction:column;gap:20rpx}.top-note{display:flex;min-height:190rpx;flex-direction:column;justify-content:center;padding:30rpx 36rpx;border-radius:18rpx 38rpx 18rpx 32rpx;background:var(--tago-note-yellow);transform:rotate(-.5deg)}.top-note text{font-size:24rpx;font-weight:800}.top-note b{margin:8rpx 0;color:var(--tago-primary);font-size:48rpx}.top-note small,.hint,.row small,.empty{color:var(--tago-muted);font-size:19rpx}.paper{padding:30rpx;border-radius:24rpx;background:rgba(255,253,247,.88);box-shadow:var(--tago-shadow)}.title{display:block;font-size:29rpx;font-weight:900}.hint{display:block;margin:9rpx 0 20rpx}.bid-box input,.lookup-box input{height:78rpx;padding:0 22rpx;border-radius:18rpx;background:var(--tago-primary-weak)}.bid-box button,.lookup-box button{height:74rpx;margin-top:18rpx;color:#fff;border-radius:999rpx;background:var(--tago-primary);font-size:24rpx;line-height:74rpx}.bid-box button::after,.lookup-box button::after{border:0}.lookup-box>view{display:grid;grid-template-columns:1fr 120rpx;gap:12rpx}.lookup-box>view button{margin-top:0}.lookup-result{display:block;margin-top:12rpx;color:var(--tago-primary);font-size:17rpx;overflow-wrap:anywhere}.rows{margin-top:16rpx}.row{display:flex;align-items:center;justify-content:space-between;gap:18rpx;padding:18rpx 4rpx;border-bottom:1px dashed var(--tago-line);font-size:22rpx}.row>view{display:flex;min-width:0;flex-direction:column}.row>text{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.row b{flex:none;color:var(--tago-primary)}.status--rejected{color:var(--tago-danger)!important}.empty{display:block;padding:30rpx 0;text-align:center} .wallet-link{margin-top:8rpx!important;color:var(--tago-primary)!important;background:transparent!important}</style>
