<script setup lang="ts">
import { onShow } from '@dcloudio/uni-app'
import dayjs from 'dayjs'
import { shallowRef } from 'vue'
import type { TagHistoryDetailDto, TagHistoryPageDto } from '@/api/social'
import { getMyTagHistory, listMyTagHistory } from '@/api/social'
import AppHeader from '@/components/business/AppHeader.vue'
import AsyncState from '@/components/ui/AsyncState.vue'
import { goBack } from '@/utils/navigation'
const page=shallowRef<TagHistoryPageDto|null>(null),detail=shallowRef<TagHistoryDetailDto|null>(null),loading=shallowRef(false),loadingMore=shallowRef(false),error=shallowRef('')
function formatTime(value?:string|null){if(!value)return'';const time=dayjs(value);return time.isValid()?time.format('YYYY-MM-DD'):value}
async function load(){loading.value=true;error.value='';try{page.value=await listMyTagHistory({limit:20})}catch(cause){error.value=cause instanceof Error?cause.message:'历史 Tag 加载失败'}finally{loading.value=false}}
async function loadMore(){if(!page.value?.hasMore||!page.value.nextCursor||loadingMore.value)return;loadingMore.value=true;try{const next=await listMyTagHistory({limit:20,cursor:page.value.nextCursor});page.value={...next,items:[...page.value.items,...next.items]}}finally{loadingMore.value=false}}
async function open(id:string){detail.value=await getMyTagHistory(id)}
function close(){detail.value=null} onShow(load)
</script>
<template><view class="tago-page tago-page--detail history-page"><AppHeader back title="历史 Tag" subtitle="回看曾经认真写下的自己" @back="goBack"/><AsyncState :loading="loading" :error="error" :empty="!page?.items.length" empty-title="还没有历史 Tag" empty-description="关闭或自然结束的 Tag 会保存在这里。" @retry="load"><view class="history-list"><button v-for="item in page?.items" :key="item.id" class="history-card" @click="open(item.id)"><view><text># {{ item.body }}</text><small>{{ formatTime(item.inactiveAt||item.expiresAt||item.publishedAt) }}</small></view><b>{{ {CLOSED:'已关闭',REPLACED:'已替换',EXPIRED:'已到期'}[item.state] }}</b></button><button v-if="page?.hasMore" class="load-more" :loading="loadingMore" @click="loadMore">加载更多</button></view></AsyncState><view v-if="detail" class="detail-mask" @click="close"><view class="detail-sheet" @click.stop><text class="detail-title"># {{ detail.body }}</text><text class="detail-meta">{{ {CLOSED:'已关闭',REPLACED:'已替换',EXPIRED:'已到期'}[detail.state] }} · {{ formatTime(detail.inactiveAt) }}</text><article v-for="q in detail.questions" :key="q.slot"><b>Q{{ q.slot }} {{ q.text }}</b><text>{{ detail.publisherAnswers.find(a=>a.slot===q.slot)?.text||'—' }}</text></article><button @click="close">收起</button></view></view></view></template>
<style scoped lang="scss">.history-list{display:flex;flex-direction:column;gap:15rpx}.history-card{display:flex;align-items:center;justify-content:space-between;width:100%;min-height:118rpx;padding:20rpx 25rpx;color:var(--tago-ink);border:0;border-radius:18rpx 27rpx;background:rgba(255,253,247,.88);box-shadow:0 6rpx 18rpx rgba(39,68,56,.07);text-align:left}.history-card::after,.load-more::after,.detail-sheet>button::after{border:0}.history-card>view{display:flex;min-width:0;flex:1;flex-direction:column}.history-card view>text{overflow:hidden;font-size:23rpx;font-weight:800;text-overflow:ellipsis;white-space:nowrap}.history-card small{margin-top:7rpx;color:var(--tago-muted);font-size:17rpx}.history-card>b{flex:none;margin-left:18rpx;color:var(--tago-primary);font-size:18rpx}.load-more{height:68rpx;color:var(--tago-primary);border:0;background:transparent;font-size:20rpx;line-height:68rpx}.detail-mask{position:fixed;z-index:50;inset:0;display:flex;align-items:flex-end;background:rgba(27,40,34,.34)}.detail-sheet{width:100%;max-height:82dvh;padding:34rpx 28rpx calc(25rpx + env(safe-area-inset-bottom));overflow:auto;border-radius:34rpx 34rpx 0 0;background:var(--tago-paper)}.detail-title{display:block;font-size:30rpx;font-weight:900;line-height:1.45}.detail-meta{display:block;margin:9rpx 0 20rpx;color:var(--tago-muted);font-size:18rpx}.detail-sheet article{display:flex;flex-direction:column;gap:10rpx;margin-bottom:15rpx;padding:20rpx;border-radius:18rpx;background:#fff}.detail-sheet article b{font-size:21rpx}.detail-sheet article text{padding:12rpx;border-radius:12rpx;background:var(--tago-primary-weak);font-size:20rpx;line-height:1.55}.detail-sheet>button{height:70rpx;color:#fff;border-radius:999rpx;background:var(--tago-primary);line-height:70rpx}</style>
